smodeal_admin_homepage:
    pattern:  /
    defaults: { _controller: SmodealAdminBundle:Admin:index }

smodeal_admin_category:
    pattern:  /categorie
    defaults: { _controller: SmodealAdminBundle:Category:index }

smodeal_admin_category_add:
    pattern:  //categorie/ajouter
    defaults: { _controller: SmodealAdminBundle:Category:add }

smodeal_admin_subcategory:
    pattern:  /sous-categorie
    defaults: { _controller: SmodealAdminBundle:Category:index }

smodeal_admin_subcategory_add:
    pattern:  /sous-categorie/ajouter
    defaults: { _controller: SmodealAdminBundle:Category:add }
