<?php

namespace Smodeal\AdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownRepository extends EntityRepository
{
}
