parameters:
#    smodeal_ad.example.class: Smodeal\AdBundle\Example

services:
#    smodeal_ad.example:
#        class: %smodeal_ad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
